---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: default
spec:
  encryptedData:
    password: AgANyqtV2GnXQ8viaJAKXzDf4jOyBRr88lRe6cKnEYeAqaFKxp59A/iXMz+2s1WZWwBWaTkV4BnLGrypY5UJG9EyXqEeNE7qsm9L6fXeqfexuj8qKRccUtqPuYS/bzIJNJH98JjA0OrRkk4RlkZfCc2Z8lfth8i6BbtJ7fBegxglX3Y+IuzzW+0MY64RNgXd1k6b07c0BM3byq2qWaIiU4arBamEHVVlvu3ntRiopeFTx5lwwo019n2SPD+0GJl25XOzJDPCyGOG+AYtJL0av5FS+pEc4LNCgXCfzwKVKQedMARe2qlswd2c2XwUthzSFRXCpYfteIY0SsDUX6SWAKSTLrmxk/hkE23AyEQ8ad1fwD0cm+ifPwt83hfOhl2o8F2cnaza7dSQDQdxjAQNIBGZM9+m4gFlKjWA3DYyd7Q2jFIto3ND/ugnMRaCgmhg2QJLhz5L7/AnaBx3f2S5zQR4VqWAp2H5z/PvXwvNL9z1CT2yTJaqSFZnNbZKyhAesv9i2P+KIahlmvAkdUBvQO2pjkmd+4Z57RoQONISl1i4lZi7FDy2/kwIBdUuvrRqFIsen25BO6JhKXwk7im3MuRjnbcEzWYU1C/CzkTRoeBX74XqnozctV8jxW4IW0KmMBs0eaEVfie64Z1WaoJpHw1iNdUqXq/6jcGSJf4/RBHXbDJ351ESdCE6DopJs3u960lDakjKxEp7Yz78Zd00eDtvtw==
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: default
    type: Opaque
